/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "surface": "#fcf8fb",
          "secondary": "#5d5e66",
          "tertiary-container": "#a44100",
          "on-primary-fixed-variant": "#3323cc",
          "outline-variant": "#c7c4d8",
          "outline": "#777587",
          "on-primary-fixed": "#0f0069",
          "on-background": "#1c1b1d",
          "secondary-fixed-dim": "#c6c5cf",
          "error": "#ba1a1a",
          "inverse-surface": "#313032",
          "tertiary-fixed-dim": "#ffb695",
          "on-secondary-fixed-variant": "#46464e",
          "on-tertiary-fixed": "#351000",
          "secondary-fixed": "#e3e1ec",
          "on-secondary": "#ffffff",
          "on-tertiary": "#ffffff",
          "surface-dim": "#dcd9dc",
          "on-secondary-fixed": "#1a1b22",
          "tertiary-fixed": "#ffdbcc",
          "inverse-on-surface": "#f3f0f2",
          "on-secondary-container": "#63646c",
          "on-error-container": "#93000a",
          "on-surface": "#1c1b1d",
          "on-primary-container": "#dad7ff",
          "surface-tint": "#4d44e3",
          "background": "#fcf8fb",
          "surface-variant": "#e5e1e4",
          "primary": "#3525cd",
          "on-tertiary-container": "#ffd2be",
          "on-surface-variant": "#464555",
          "on-tertiary-fixed-variant": "#7b2f00",
          "surface-bright": "#fcf8fb",
          "on-primary": "#ffffff",
          "tertiary": "#7e3000",
          "primary-fixed": "#e2dfff",
          "primary-fixed-dim": "#c3c0ff",
          "surface-container-low": "#f6f2f5",
          "error-container": "#ffdad6",
          "inverse-primary": "#c3c0ff",
          "primary-container": "#4f46e5",
          "surface-container-high": "#eae7ea",
          "surface-container": "#f0edf0",
          "on-error": "#ffffff",
          "secondary-container": "#e3e1ec",
          "surface-container-lowest": "#ffffff",
          "surface-container-highest": "#e5e1e4"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "spacing": {
          "12": "3rem",
          "0": "0",
          "1": "0.25rem",
          "4": "1rem",
          "2": "0.5rem",
          "6": "1.5rem",
          "container-max": "1440px",
          "8": "2rem",
          "3": "0.75rem",
          "gutter": "1.5rem",
          "16": "4rem"
      },
      "fontFamily": {
          "label-md": ["Inter"],
          "headline-lg-mobile": ["Inter"],
          "code": ["JetBrains Mono"],
          "headline-lg": ["Inter"],
          "title-md": ["Inter"],
          "headline-md": ["Inter"],
          "body-lg": ["Inter"],
          "body-md": ["Inter"],
          "display": ["Inter"]
      },
      "fontSize": {
          "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
          "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "code": ["13px", {"lineHeight": "20px", "fontWeight": "400"}],
          "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
          "title-md": ["18px", {"lineHeight": "28px", "fontWeight": "600"}],
          "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
          "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
          "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
          "display": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
